version: '3.8'
services:
  frontend:
    image: 20240817_nextjs:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
